
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-backend
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
spec:
  ports:
    - port: 3306
  selector:
    app: databasemysql
  clusterIP: None

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-ingress
spec:
  podSelector: {}
  ingress:
  - {}
  policyTypes:
  - Ingress